export const ERRORS = {
  VALIDATION_ERROR: "ERROR_VALIDATION_ERROR",
  INVALID_FILE_TYPE: "ERROR_INVALID_FILE_TYPE",
  FILE_REQUIRED: "ERROR_FILE_REQUIRED",
  EXPIRED: "ERROR_EXPIRED",

  ACCESS_TOKEN_EXPIRED: "ERROR_ACCESS_TOKEN_EXPIRED",
  ACCESS_TOKEN_MISSING: "ERROR_ACCESS_TOKEN_MISSING",

  REFRESH_TOKEN_EXPIRED: "ERROR_REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_MISSING: "ERROR_REFRESH_TOKEN_MISSING",

  UNAUTHENTICATED: "ERROR_UNAUTHENTICATED",
  UNAUTHORIZED: "ERROR_UNAUTHORIZED",
  FORBIDDEN: "ERROR_FORBIDDEN",

  TOO_MANY_REQUESTS: "ERROR_TOO_MANY_REQUESTS",

  EMAIL_ALREADY_TAKEN: "ERROR_EMAIL_ALREADY_TAKEN",
  INVALID_CREDENTIALS: "ERROR_INVALID_CREDENTIALS",
  NOT_FOUND: "ERROR_NOT_FOUND",

  INTERNAL_SERVER_ERROR: "ERROR_INTERNAL_SERVER_ERROR",
  CORS_ERROR: "ERROR_CORS_ERROR",
};

export const CACHE_KEYS = {
  POSTS: "posts:",
  ARTICLES: "articles:",
  USERS: "users:",
};
